version: "3.3"

services:
  db:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./db/data:/var/lib/mongodb

  api:
    build: './'
    restart: always
    volumes:
      - ./:/app
    ports:
      - '9001:9001'
    depends_on:
      - db
    command: npm run nodemon:dev
